import { ArrowRight, BatteryCharging, CalendarCheck2, CheckCircle2, MapPinned, ShieldCheck, UsersRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import heroImage from '../assets/wide_clean_modern_minimalistic_tech_ev_charging.png'
import { Brand } from '../components/shell/AppShell'

export function LandingPage() {
  return <div className="landing-page landing-page--refined">
    <header className="landing-header"><Brand /><nav><a href="#how-it-works">How it works</a><a href="#community">Community</a><Link to="/login" className="landing-login">Log in</Link><Link to="/register" className="landing-cta">Get started <ArrowRight size={16} /></Link></nav></header>
    <main>
      <section className="hero-section hero-section--split"><div className="hero-copy"><span className="hero-kicker">Charging for everyday journeys</span><h1>Find a charger.<br /><em>Reserve your slot.</em></h1><p>Find available public and community chargers, then reserve a time that works for you.</p><div className="hero-actions"><Link to="/discover" className="button button--dark">Find a charger <ArrowRight size={18} /></Link><Link to="/login?role=OWNER" className="button button--secondary">Share your charger</Link></div></div><div className="hero-visual"><img src={heroImage} alt="Electric vehicle charging at a modern Plug-In station" /></div></section>
      <section className="trust-strip"><span><CheckCircle2 size={18} /> Availability you can check</span><span><ShieldCheck size={18} /> Verified community listings</span><span><MapPinned size={18} /> Built for local charging</span></section>
      <section className="section-block" id="how-it-works"><div className="section-heading"><span className="hero-kicker">How it works</span><h2>Find a charger and reserve your slot.</h2><p>Plug-In gives drivers and charger owners one place to manage local charging.</p></div><div className="steps-grid"><article><MapPinned size={24} /><h3>Find nearby</h3><p>Search public stations and community chargers on the map.</p></article><article><CalendarCheck2 size={24} /><h3>Reserve a time</h3><p>Check availability and choose a charging window.</p></article><article><BatteryCharging size={24} /><h3>Charge with confidence</h3><p>Arrive with the details you need for your stop.</p></article></div></section>
      <section className="community-section" id="community"><div className="community-section__copy"><span className="hero-kicker">Community charging</span><h2>Share your charger with nearby drivers.</h2><p>Set your hours, price, and capacity. Plug-In helps people discover and reserve available charging in their area.</p><ul><li><CheckCircle2 size={18} /> Choose when your charger is available</li><li><CheckCircle2 size={18} /> Manage reservations in one place</li><li><CheckCircle2 size={18} /> Keep listings accurate with reporting</li></ul><Link to="/login?role=OWNER" className="text-link text-link--large">Share a charger <ArrowRight size={17} /></Link></div><div className="community-summary"><UsersRound size={28} /><h3>Make local charging more accessible.</h3><p>Community listings appear alongside public stations, with availability and reservation details.</p></div></section>
      <section className="closing-cta"><h2>Find your next charging stop.</h2><p>Search availability, reserve a slot, and get on the road.</p><Link to="/discover" className="button button--primary">Explore chargers <ArrowRight size={17} /></Link></section>
    </main><footer className="landing-footer"><Brand /><span>Find. Reserve. Charge. Share.</span><span>Plug-In · Community EV charging</span></footer>
  </div>
}
